spring.application.name=resume-analyzer

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres}

spring.datasource.username=${DATABASE_USERNAME:postgres.vrivnxkzxdehaldapsbl}

spring.datasource.password=${DATABASE_PASSWORD:Spoorthi@123!@}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
